(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: Solver.m *)
(* Context: *)
(* Author:oliver ruebenkoenig *)
(* 
  Date: 1.3.2005, Freiburg,IL *)
(* Summary: Mathematica Ax=f solver *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.1 *)
(* 
  Mathematica Version: 4.2 *)
(* History: *)
(* Keywords: *)
(* Sources: *)
(* 
  Warnings: *)
(* Limitations: *)
(* Discussion: *)
(* Requirements: *)
(* 
  Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* Mathematica Ax=f solver *)

(* Copyright (C) 2003-2005 *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)
BeginPackage["Imtek`AlgebraicSolver`"];





(* *)
(* documentation *)
(* *)
Needs["Imtek`Maintenance`"]
imsCreateObsoleteFunctionInterface[ JacobiStep, $Context ];
imsCreateObsoleteFunctionInterface[ JacobiSolve, $Context ];
imsCreateObsoleteFunctionInterface[ GaussSeidelStep, $Context ];
imsCreateObsoleteFunctionInterface[ GaussSeidelSolve, $Context ];
imsCreateObsoleteFunctionInterface[ SORStep, $Context ];
imsCreateObsoleteFunctionInterface[ SORSolve, $Context ];

(* constructors *)

(* selectors *)

(* predicates *)

(* functions *)

imsJacobiStep::usage = "imsJacobiStep[ matrix, load, guess, omega ] advances the solution of the matrix equation with load by one step. starting from guess and with given omega."
\

imsJacobiSolve::usage = 
  "imsJacobiSolve[ matrix, load, guess, iterations, omega ] tries to solve the system given by the matrix and load vector it uses guess to start and proceeds number of iterations. Optionaly a different omega can be supplied, the default is 1." \


imsGaussSeidelStep::usage = "imsGaussSeidelStep[ matrix, load, guess ] advances the solution of the matrix equation with load by one step, starting from guess."
\

imsGaussSeidelSolve::usage = 
  "imsGaussSeidelSolve[ matrix, load, guess, iterations ] tries to solve the system given by the matrix and load vector it uses guess to start and proceeds number of iterations." \


imsSORStep::usage = "imsSORStep[ matrix, load, guess, omega ] advances the solution of the matrix equation with load by one step. starting from guess and with given omega."
\

imsSORSolve::usage = 
  "imsSORSolve[ matrix, load, guess, iterations, omega ] tries to solve the system given by the matrix and load vector it uses guess to start and proceeds number of iterations. Optionaly a different omega can be supplied, the default is 1." \





(* *)
(* options docu *)
(* *)



(* *)
(* Error Messages *)
(* *)





(* *)
(* implementation part *)
(* *)

(* constructor *)



Begin["`Private`"];





(* *)
(* define your options *)
(* *)



(* selector *)



(* predicates *)



(* functions *)
(* Jacobi *)

JacobiRowStep[ row_, loadi_, guess_, i_ ] := 
    loadi - Plus @@ Drop[ row * guess, {i} ];

imsJacobiStep[ matrix_, load_, guess_, omega_ ] :=
    Module[
      { i = 1 },
      ( 1 - omega) * guess +
        Map[  omega/matrix[[ i, i ]] * 
              JacobiRowStep[ #, load[[ i ]], guess, i++ ]&, matrix ]
      ];

imsJacobiSolve[ matrix_, load_,  guess_, iter_, omega_:1.0 ] := 
  Nest[ imsJacobiStep[ matrix, load, #, omega ]&, N[ guess ], iter ] /; 
    MatrixQ[ matrix ] && Length[ guess ] \[Equal] Length[ load ]

(* Gauss Seidel *)

imsGaussSeidelStep[ matrix_, load_, guess_ ] :=
    
    imsSORStep[ matrix, load, guess, 1.0 ];

imsGaussSeidelSolve[ matrix_, load_, guess_, iter_ ] := 
  Nest[ imsGaussSeidelStep[ matrix, load, # ]&, N[ guess ],iter ]/; 
    MatrixQ[ matrix ] && Length[ guess ] \[Equal] Length[ load ]

(* SOR *)
imsSORStep[ matrix_, load_, guessIn_, omega_ ] :=
    Module[
      { i = 1, guess = guessIn },
      
      Do[
        guess[[i]] = (1-omega)* guess[[i]] + 
              omega/ matrix[[ i, i ]] * 
                JacobiRowStep[  matrix[[ i ]],load[[ i ]], guess, i ];
        ,{ i, Last[ Dimensions[ matrix ] ] }
        ];
      Return[ guess ];
      ];

imsSORSolve[ matrix_, load_, guess_, iter_, omega_:1.0 ] := 
  Nest[ imsSORStep[ matrix, load, #, omega ]&, N[ guess ],iter ]/; 
    MatrixQ[ matrix ] && Length[ guess ] \[Equal] Length[ load ]



End[] (* of Begin Private *)



(* Protect[] (* anything *) *)
EndPackage[] 
