(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: BackwardCompatability.m *)
(* Context: *)
(* 
  Author:jan lienemann + oliver ruebenkoenig *)
(* Date: 23.11.2006, 
  Freiburg + Leipzig *)
(* 
  Summary: This is packages for providing mathematica 5.2 and 5.1 \
functinality in 5.0 *)
(* Package Copyright: GNU GPL *)
(* 
  Package Version: 0.1.1 *)
(* Mathematica Version: 5.2 *)
(* 
  History: Had to remove the Evaluate inside the If statement *)
(* 
  Keywords: *)
(* Sources: *)
(* Warnings: *)
(* Limitations: *)
(* 
  Discussion: *)
(* Requirements: *)
(* Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* This is packages for providing mathematica 5.2 and 5.1 functinality in 5.0 \
*)

(* Copyright (C) 2006 jan lienemann + oliver ruebenkoenig *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)
BeginPackage["Imtek`BackwardCompatability`"];





(* *)
(* documentation *)
(* *)

(* constructors *)

imsProvideSymbolIfNotDefined::usage="imsProvideSymbolIfNotDefined[s_String, exp_String] ataches the string s to the System` context with exp as evaluation rule.";\


(* selectors *)

(* predicates *)

(* functions *)




(* *)
(* options docu *)
(* *)



(* *)
(* error messages *)
(* *)



Begin["`Private`"];



(* *)
(* private imports *)
(* *)



(* *)
(* implementation part *)
(* *)

(* constructor *)
(* *)
SetAttributes[imsProvideSymbolIfNotDefined,HoldAll]

imsProvideSymbolIfNotDefined[s_String,t_String]:=
    If[Names[s]==={},ToExpression[t]];



(* *)
(* define your options *)
(* *)



(* selector *)
(* *)



(* predicates *)
(* *)



(* private functions *)
(* *)

(* public functions *)
(* *)
(* does NOT work for strings *)

imsProvideSymbolIfNotDefined[ "System`Except",
    "
    System`Except[c_]:=_?(!MatchQ[#,c]&);
    System`Except[c_,p_]:=_?(!MatchQ[#,c]&&MatchQ[#,p]&);
    System`Except::usage=\"Except[c] is a pattern object which represents any expression except one that matches c.\n\nExcept[c, p] represents any expression that matches p but not c.\"
    "
    ];



(* representors *)
(* *)



(* Begin Private *)
End[]



(* Protect[] *)
EndPackage[] 
