(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: BDF.m *)
(* Context: *)
(* Author:oliver ruebenkoenig *)
(* 
  Date: 23.10.2007, Freiburg *)
(* 
  Summary: This is the IMTEK template for writing a mathematica packages *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.1 *)
(* 
  Mathematica Version: 5.2 *)
(* History: *)
(* Keywords: *)
(* Sources: *)
(* 
  Warnings: *)
(* Limitations: *)
(* Discussion: *)
(* Requirements: *)
(* 
  Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* this package provides a bdf step and a bdf solution procedure *)

(* Copyright (C) 2007 oliver ruebenkoenig *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)
BeginPackage["Imtek`BDF`",{"Imtek`NonlinearSolve`"}];





(* *)
(* documentation *)
(* *)

(* constructors *)

(* selectors *)

(* predicates *)

(* functions *)

imsBDFCoefficients::usage="imsBDFCoefficients[ order ] returns a list of coefficients. Order is an integer between 1 and 6.";\

imsBDFStep::usage="imsBDFStep[ f, j, m, oldVals, currentTime, dt, coeffs, opts ] returns a list where the stystem of equations f, its mass matrix m and its jacobian have been advanced from the current time by the time step dt. The coefficients can be any given by imsBDFCoefficients. For an order n coefficients n-2 old solution values are needed. Theoptions are for imsNonlinearSolve.";\

imsBDFSolve::usage="imsBDFSolve[ f, j, m, oldVals, { tStart, tEnd, dt }, coeffs, opts ] returns a list composed of two lists. The first list contains the computed time steps from tStart to tEnd in dt step. The second list contains the result to the system of equations described by f and the jacobian and the mass matrix. The coefficients can be any given by imsBDFCoefficients. For an order n-2 coefficients n old solution values are needed. Theoptions are for imsNonlinearSolve.";



(* *)
(* options docu *)
(* *)



(* *)
(* error messages *)
(* *)



Begin["`Private`"];



(* *)
(* private imports *)
(* *)
<<Developer`
Needs["Imtek`SparseUtils`"]



(* *)
(* implementation part *)
(* *)

(* constructor *)
(* *)



(* *)
(* define your options *)
(* *)



(* selector *)
(* *)



(* predicates *)
(* *)



(* private functions *)
(* *)

(* public functions *)
(* *)
(*
  
  imsBDFStep[ f_, j_,oldy_,currentTime_, dt_, coeffs_, opts___?OptionQ ] := 
    Module[
      { bk=1, g, m, tail },
      tail = Plus @@ Times[ Most[ coeffs ], oldy ];
      g[ un_List ] := 
        coeffs[[-1]] * un - dt * bk * f[ currentTime+dt, un ] + tail;
      m[ un_List ] := 
        imsSparseDiagonalMatrix[ Table[ coeffs[[-1]], {Length[un]} ], 0. ]  - 
          dt * bk * j[ currentTime+dt, un ];
      imsNonlinearSolve[ m, g, oldy[[-1]], opts ]
      ]
  *)

imsBDFStep[f_,jacobian_,mass_,oldVals_,currentTime_,dt_,coeffs_,
      opts___?OptionQ]:=Module[
      {bk=1/coeffs[[-1]],g,m,tail},
      tail=(Plus@@Times[Most[coeffs],oldVals])/coeffs[[-1]];
      g[un_List]:=
        mass[currentTime+dt,un].(un+tail)-dt*bk*f[currentTime+dt,un];
      m[un_List]:=mass[currentTime+dt,un]-dt*bk*jacobian[currentTime+dt,un];
      imsNonlinearSolve[m,g,oldVals[[-1]],opts]
      ];

(*
  imsBDFSolve[ f_, j_, oldVals_, { tStart_, tEnd_, dt_}, coeffs_,
      opts___?OptionQ ] := 
    Block[ { thisVals = 
          RotateRight[ oldVals ] },{ Partition[ Join[ #, {tEnd} ], 1 ] , 
            ToPackedArray[ 
              FoldList[ 
                imsBDFStep[ f, j, thisVals = Rest[ Join[ thisVals, {#1} ] ];
                    thisVals,#2, dt, coeffs, opts ]&, 
                Last[ oldVals ], # ] ] }&[Range[tStart, tEnd-dt, dt]]
      ]
  *)

imsBDFSolve[ f_, j_, m_, oldVals_, { tStart_, tEnd_, dt_ }, coeffs_, 
    opts___?OptionQ ] := Block[
    { thisVals = RotateRight[ oldVals ] },
    { Partition[ Join[ #, { tEnd } ], 1 ], 
          ToPackedArray[ 
            FoldList[ 
              imsBDFStep[ f, j, m, thisVals=Rest[ Join[ thisVals, { #1 } ] ];
                   thisVals, #2, dt, coeffs, opts ]&, 
              Last[ oldVals ], # ] ] }&[ Range[ tStart, tEnd-dt, dt ] ] ]

(*
  imsBDFCoefficients[ 1 ]:= {-1,1};
  imsBDFCoefficients[ 2 ]:= {1/2,-2,3/2};
  imsBDFCoefficients[ 3 ]:= {-1/3,3/2,-3,11/6};
  imsBDFCoefficients[ 4 ]:= {1/4,-4/3,3,-4,25/12};
  imsBDFCoefficients[ 5 ]:= {-1/5,5/4,-10/3,5,-5,137/60};
  imsBDFCoefficients[ 6 ]:= {1/6,-6/5,15/4,-20/3,15/2,-6,49/20};
  *)

imsBDFCoefficients[1]:={-1,1};
imsBDFCoefficients[2]:={1/2,-2,3/2};
imsBDFCoefficients[3]:={-1/3,3/2,-3,11/6};
imsBDFCoefficients[4]:={1/4,-4/3,3,-4,25/12};
imsBDFCoefficients[5]:={-1/5,5/4,-10/3,5,-5,137/60};
imsBDFCoefficients[6]:={1/6,-6/5,15/4,-20/3,15/2,-6,49/20};



(* representors *)
(* *)



(* Begin Private *)
End[]



(* Protect[] *)
EndPackage[] 
