(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: DomainElementLibrary.m *)
(* Context: *)
(* 
  Author:oliver ruebenkoenig *)
(* Date: 16.11.05, Leipzig to Freiburg *)
(* 
  Summary: This is the IMTEK domain element library *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.1.2 *)
(* 
  Mathematica Version: 5.2 *)
(* History: *)
(* performance improvement *)
(* 
  Keywords: *)
(* Sources: *)
(* Warnings: *)
(* Limitations: *)
(* 
  Discussion: *)
(* Requirements: *)
(* Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* This is the IMTEK domain element library. 
      Extend Graph to deal with domain elements *)

(* Copyright (C) 2005, oliver ruebenkoenig *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)

BeginPackage["Imtek`DomainElementLibrary`", "Imtek`Nodes`", "Imtek`Graph`"];





(* *)
(* documentation *)
(* *)

(* constructors *)

imsMakeDomainSegment::usage="imsMakeDomainSegment[ id, nodeIds, marker, data ] returns an imsDomainSegment with Integer id and a List of nodeIdes. Marker defaults to 0. Optionally data can be given.";\

imsDomainSegment::usage="";

imsMakeDomainHoleSegment::usage="imsMakeDomainSegment[ id, nodeIds, marker, data ] returns an imsDomainSegment with Integer id and a List of nodeIdes. Marker defaults to 0. Optionally data can be given.";\

imsDomainHoleSegment::usage="";

(* selectors *)

imsGetIds::usage="imsGetIds[ elements ] returns the elements id.";
imsGetIncidentsIds::usage="imsGetIncidentsIds[ elements ] returns the elements nodeIds.";\

imsGetMarkers::usage="imsGetMarkers[ elements ] returns the elements marker.";\

imsGetDatas::usage="imsGetDatas[ elements ] returns the element's data, if any are present.";\


(* predicates *)

imsDomainElementQ::usage="imsDomainElementQ[ expr ] returns True if expr is a domain element.";\

imsDataDomainElementQ::usage = "imsDataDomainElementQ[ expr ] returns True if expr is a domain element containing data."
\

(* functions *)

imsGraphics3DToNexus::usage = \
"imsGraphics3DToNexus[ Graphics3D ] returns an imsNexus from Graphics3D with boundary nodes set to imsNodes and elements set to imsDomainSegments.";\


(* representors *)

imsDrawElements::usage="imsDrawElements[ element, nodes ] will draw the element consisting of nodes.";\

imsDrawElementIdText::usage="imsDrawElementIdText[ element, nodes ] will draw the element's id as text. The element is made up from nodes.";



(* *)
(* options docu *)
(* *)



(* *)
(* error messages *)
(* *)



Begin["`Private`"];



(* *)
(* private imports *)
(* *)
Needs["Imtek`Polygon`"];



(* *)
(* implementation part *)
(* *)

(* constructor *)
(* *)

imsMakeDomainSegment[ id_, nodeIds_List, marker_Integer:0, data___ ] := 
    imsDomainSegment[ id, nodeIds, marker, data ];

imsMakeDomainHoleSegment[ id_, nodeIds_List, marker_Integer:0, data___ ] := 
    imsDomainHoleSegment[ id, nodeIds, marker, data ];



(* *)
(* define your options *)
(* *)



(* selector *)
(* *)
imsGetIds[ a_imsDomainSegment ] := a[[ 1 ]];
imsGetIncidentsIds[ a_imsDomainSegment ] := a[[ 2 ]];
imsGetMarkers[ a_imsDomainSegment ] := a[[ 3 ]];
imsGetDatas[ a_imsDomainSegment ] := a[[ 4 ]];

imsGetIds[ a_imsDomainHoleSegment ] := a[[ 1 ]];
imsGetIncidentsIds[ a_imsDomainHoleSegment ] := a[[ 2 ]];
imsGetMarkers[ a_imsDomainHoleSegment ] := a[[ 3 ]];
imsGetDatas[ a_imsDomainHoleSegment ] := a[[ 4 ]];



(* predicates *)
(* *)
imsDomainElementQ[ _imsDomainSegment ] := True;
imsDomainElementQ[ _imsDomainHoleSegment ] := True;
imsDomainElementQ[ ___ ] := False;

imsDataDomainElementQ[ imsDomainSegment[ _, _, _, _ ] ] := True;
imsDataDomainElementQ[ imsDomainHoleSegment[ _, _, _, _ ] ] := True;
imsDataDomainElementQ[ ___ ] := False;



(* private functions *)
(* *)

imsPolygonToDomainSegements[ polygons_ ] := Module[
      { i, f, boundaryNodes, domainSegments, coords, incidents },
      
      coords = Union[ Flatten[ List @@@ Flatten[ polygons ], 2 ] ];
      
      i=1;
      (f[ # ]=i++)&/@coords;
      incidents = Map[ f, (Sequence @@@ polygons), {2} ];
      
      i = 1;
      boundaryNodes = imsMakeNode[ i++, # ]& /@ coords;
      
      i=1;
      domainSegments = imsMakeDomainSegment[ i++,  # ]& /@ incidents;
      
      Return[{ boundaryNodes, domainSegments }];
      ];

(* public functions *)
(* *)
imsGraphics3DToNexus[ gr_Graphics3D ] := Module[
      { polygons, boundaryNodes, elements },
      
      (* dirty, dirty... *)
      
      polygons = Cases[ Flatten[ List @@ gr ], _Polygon ];
      
      { boundaryNodes, elements } = imsPolygonToDomainSegements[ polygons ];
      
      Return[ imsMakeNexus[ boundaryNodes, {}, elements ] ];
      ];



(* representors *)
(* *)

imsDrawElements[ e_imsDomainSegment, nodes_ ]:= 
    Line[ imsClosePolygon[ imsGetCoords[ nodes ] ] ];
imsDrawElements[ e_imsDomainHoleSegment, nodes_ ]:= 
    Line[ imsClosePolygon[ imsGetCoords[ nodes ] ] ];



(* Begin Private *)
End[]



(* Protect[] *)
EndPackage[] 
