(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: FEMMecchanics.m *)
(* Context: *)
(* 
  Author: Benjamin Lemke / Christian Moosmann / Oliver Ruebenkoenig *)
(* 
  Date: 2005/01/10, Freiburg *)
(* Summary:  *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.2 *)
(* 
  Mathematica Version: 5.0 *)
(* History: *)
(* 
  Keywords: mechanics, stress, strain *)
(* Sources: *)
(* Warnings: *)
(* 
  Limitations: *)
(* Discussion: *)
(* Requirements: *)
(* Examples: *)
(* *)



(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)


(* Copyright (C) 2005 Benjamin Lemke *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)
BeginPackage["Imtek`FEMMechanics`", "Imtek`FEMOperators`"]





(* *)
(* documentation *)
(* *)

imsFEMPlaneStress::usage=
    "imsFEMPlaneStress[ { elementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, 
    	{ n1, n2, n3 }, mechanicalFunction] returns the new elementOperatorMatrix and the new elementRHS."
\
  
  imsNFEMPlaneStress::usage=
    "imsNFEMPlaneStress[ { elementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, 
    	{ n1, n2, n3 }, mechanicalFunction] returns a numeric elementOperatorMatrix and the numeric elementRHS."
\
  
  imsFEMPlaneStrain::usage=
    "imsFEMPlaneStrain[ {ElementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, 
    	{ n1, n2, n3 }, mechanicalFunction] returns the new elementOperatorMatrix and the new elementRHS."
\
  
  imsNFEMPlaneStrain::usage=
    "imsNFEMPlaneStrain[ {ElementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, 
    	{ n1, n2, n3 }, mechanicalFunction] returns a numeric elementOperatorMatrix and the numeric elementRHS."
\
  
   imsFEMMechanicsLoad::usage=
    "imsFEMMechanicsLoad[{ elementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, 
    	{ n1, n2, n3 },f] adds a bodyforce to the elementOperatorMatrix and the elementRightHandSide."
\
  
  imsNFEMMechanicsLoad::usage="imsNFEMMechanicsLoad[{ elementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, 
    	{ n1, n2, n3 },f] numerically adds a bodyforce to the elementOperatorMatrix and the elementRightHandSide."
\
  
  imsFEMMechanicsTransientMatrix::usage=
    "imsFEMMechanicsBodyLoad[{ elementOperatorMatrix, elementRightHandSide}, imsTriangleLinear2DOF, { n1, n2, n3 },f] adds a bodyforce to the elementOperatorMatrix and the elementRightHandSide."
\
  
  imsNFEMMechanicsTransientMatrix::usage="";



Begin["`Private`"];



(* *)
(* define your options *)
(* *)



(* predicates *)



Needs["Imtek`Assembler`"]
Needs["Imtek`Nodes`"]
Needs["Imtek`Triangle`"]
Needs["Imtek`Polygon`" ]
Needs["Imtek`MeshElementLibrary`"]




compiledArea=
    Compile[{x1,y1,x2,y2,x3,y3},
      Evaluate[imsArea[{{x1,y1},{x2,y2},{x3,y3}}]]];

ccom=Compile[{x1,y1,x2,y2,x3,y3},
      Evaluate[N[imsCenterOfMass[{{x1,y1},{x2,y2},{x3,y3}}]]]];


femMechanics[{elementOperatorMatrix_,elementRightHandSide_},
      te2dof_,{n1_,n2_,n3_},CM_]:=Module[
      {x1,x2,x3,y1,y2,y3,inElementOperatorMatrix,inElementRHSMatrix,triAng,
        area,b },
      
      {{ x1, y1 }, { x2, y2 },{ x3, y3 } } = imsGetCoords[ { n1,n2,n3 } ];
      
      area =imsArea[{{x1,y1},{x2,y2},{x3,y3}}];
      
      b = {   { y2-y3, 0,y3-y1, 0,y1-y2, 0 },
          	 { 0, x3-x2, 0, x1-x3 , 0, x2-x1},
          	 {x3-x2,y2-y3,x1-x3, y3-y1,x2-x1, y1-y2 } };
      
      newElementOperatorMatrix=
        imsGetElementMatrixValues[elementOperatorMatrix];
      
      newElementOperatorMatrix +=1 /(4 area )* Transpose[ b ]. CM . b;
      
      Return[
        {
          imsMakeElementMatrix[
            newElementOperatorMatrix,
            imsGetElementMatrixRows[ elementOperatorMatrix],
             imsGetElementMatrixColumns[ elementOperatorMatrix]
            ],
          elementRightHandSide } ];
      
      ];

nFemMechanics[{elementOperatorMatrix_,elementRightHandSide_},
      te2dof_,{n1_,n2_,n3_},CM_]:=Module[
      {x1,x2,x3,y1,y2,y3,newElementOperatorMatrix,triAng,area,b },
      
      {{ x1, y1 }, { x2, y2 },{ x3, y3 } } = imsGetCoords[ { n1,n2,n3 } ];
      
      (* triAng = {{x1,y1},{x2,y2},{x3,y3}};
        area = imsArea[triAng]; *)
      
      area =compiledArea@@ {x1,y1,x2,y2,x3,y3};
      
      b = { { y2-y3, 0.,y3-y1, 0.,y1-y2, 0. }, { 0., x3-x2, 0., x1-x3 , 0., 
            x2-x1}, {x3-x2,y2-y3,x1-x3, y3-y1,x2-x1, y1-y2 } };
      
      newElementOperatorMatrix=
        imsGetElementMatrixValues[elementOperatorMatrix];
      
      newElementOperatorMatrix +=0.25 / area * Transpose[ b ]. CM . b;
      
      Return[
        {
          imsMakeElementMatrix[
            newElementOperatorMatrix,
            imsGetElementMatrixRows[ elementOperatorMatrix],
             imsGetElementMatrixColumns[ elementOperatorMatrix]
            ],
          elementRightHandSide } ];
      ];





imsFEMMechanicsTransientMatrix[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ},
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},skalar_]:=Module[
      {x1,x2,x3,y1,y2,y3,newElementOperatorMatrix,inElementRHSMatrix,triAng,
        area,stencil},
      
      {{ x1, y1 }, { x2, y2 },{ x3, y3 } } = imsGetCoords[ { n1,n2,n3 } ];
      
      newElementOperatorMatrix=
        imsGetElementMatrixValues[elementOperatorMatrix];
      
      triAng={{x1,y1},{x2,y2},{x3,y3}};
      area =imsArea[triAng];
      
      stencil={{1/6,0,1/12,0,1/12,0},{0,1/6,0,1/12,0,1/12},{1/12,0,1/6,0,1/12,
            0},{0,1/12,0,1/6,0,1/12},{1/12,0,1/12,0,1/6,0},{0,1/12,0,1/12,0,
            1/6}};
      
      newElementOperatorMatrix =skalar*area * stencil;
      
      Return[
        {
          imsMakeElementMatrix[
            newElementOperatorMatrix,
            imsGetElementMatrixRows[ elementOperatorMatrix],
             imsGetElementMatrixColumns[ elementOperatorMatrix]
            ],
          elementRightHandSide } ];
      
      ];

imsFEMPlaneStress[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ},
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},mechanicalFunction_ ]:=

        Module[
      {output, CM,marker,CMValues},
      CM[ Y_, poi_ ] := Y/(1-poi^2)*{{1,poi,0},{poi,1,0},{0,0,(1-poi)/2}};
      marker = imsGetMarkers[ te2dof ];
      { { x1, y1 },{ x2, y2 }, { x3, y3 } }  = 
        imsGetCoords[ { n1, n2, n3 } ];
      { xc, yc } = imsCenterOfMass[ { { x1, y1 },{ x2, y2 }, { x3, y3 } } ];
      
      CMValues = CM @@ ( mechanicalFunction @@ { marker, xc, yc } );
      
      femMechanics[{elementOperatorMatrix,elementRightHandSide},
        te2dof,{n1,n2,n3},CMValues ]
      ];

imsFEMPlaneStrain[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ},
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},mechanicalFunction_]:=

        Module[
      {output, CM,marker,CMValues},
      CM[ Y_, poi_ ] :=
        Y*(1-poi)/((1+poi)*(1-2*poi)){{1,poi/(1-poi),0},{poi/(1-poi),1,0},{0,
              0,(1-2*poi)/(2*(1-poi))}};
      marker = imsGetMarkers[ te2dof ];
      { { x1, y1 },{ x2, y2 }, { x3, y3 } }  = 
        imsGetCoords[ { n1, n2, n3 } ];
      { xc, yc } = imsCenterOfMass[ { { x1, y1 },{ x2, y2 }, { x3, y3 } } ];
      
      CMValues = CM @@ ( mechanicalFunction @@ { marker, xc, yc } );
      
      femMechanics[{elementOperatorMatrix,elementRightHandSide},
        te2dof,{n1,n2,n3},CMValues ]
      ];

imsFEMMechanicsLoad[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ}, 
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},f_Function]:=
    
    Module[{A,bfX,bfY,tri,comX,comY,marker, newElementRHS, outElementRHS},
      tri=imsGetCoords[ { n1,n2,n3 } ];
      A=imsArea[tri];
      {comX,comY}=imsCenterOfMass[ tri ];
      marker=imsGetMarkers[te2dof];
      {bfX,bfY}=f[marker,comX,comY];
      newElementRHSMatrix=
        imsGetElementMatrixValues[elementRightHandSide]+
          A/3{{bfX} , {bfY} , {bfX} , {bfY} , {bfX} , {bfY}};
      outElementRHS=
        imsMakeElementMatrix[ newElementRHSMatrix , 
          imsGetElementMatrixRows[ elementRightHandSide] , {1} ];
      {elementOperatorMatrix,outElementRHS}
      ];



imsNFEMPlaneStress[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ},
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},mechanicalFunction_ ]:=

        Module[
      {CM,marker,CMValues},
      CM[ Y_, poi_ ] := 
        Y/(1.-poi^2)*{{1.,poi,0.},{poi,1.,0.},{0.,0.,(1.-poi)/2.}};
      marker = imsGetMarkers[ te2dof ];
      { { x1, y1 },{ x2, y2 }, { x3, y3 } }  = 
        imsGetCoords[ { n1, n2, n3 } ];
      
      (* { xc, yc } = 
            imsCenterOfMass[ { { x1, y1 },{ x2, y2 }, { x3, 
                  y3 } } ]; *)
      
      { xc, yc } = ccom @@ {x1,y1,x2,y2,x3,y3};
      
      CMValues = CM @@ ( mechanicalFunction @@ { marker, xc, yc } );
      
      nFemMechanics[{elementOperatorMatrix,elementRightHandSide},
        te2dof,{n1,n2,n3},CMValues ]
      ];

imsNFEMPlaneStrain[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ},
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},mechanicalFunction_]:=

        Module[
      {CM,marker,CMValues},
      CM[ Y_, poi_ ] :=
        Y*(1.-poi)/((1.+poi)*(1.-2.*poi)){{1.,poi/(1.-poi),0.},{poi/(1.-poi),
              1.,0.},{0.,0.,(1.-2.*poi)/(2.*(1.-poi))}};
      marker = imsGetMarkers[ te2dof ];
      { { x1, y1 },{ x2, y2 }, { x3, y3 } }  = 
        imsGetCoords[ { n1, n2, n3 } ];
      
      (* { xc, yc } = 
            imsCenterOfMass[ { { x1, y1 },{ x2, y2 }, { x3, 
                  y3 } } ]; *)
      
      { xc, yc } = ccom @@ {x1,y1,x2,y2,x3,y3};
      
      CMValues = CM @@ ( mechanicalFunction @@ { marker, xc, yc } );
      
      nFemMechanics[{elementOperatorMatrix,elementRightHandSide},
        te2dof,{n1,n2,n3},CMValues ]
      ];

imsNFEMMechanicsLoad[{elementOperatorMatrix_?imsElementMatrixQ,
        elementRightHandSide_?imsElementMatrixQ}, 
      te2dof_,{n1_?imsNodeQ,n2_?imsNodeQ,n3_?imsNodeQ},f_Function]:=
    
    Module[{x1,y1,x2,y2,x3,y3,area,bfX,bfY,tri,comX,comY,marker, 
        newElementRHS, outElementRHS},
      
      {{ x1, y1 }, { x2, y2 },{ x3, y3 } } = imsGetCoords[ { n1,n2,n3 } ];
      
      area =compiledArea@@ {x1,y1,x2,y2,x3,y3};
      
      {comX,comY} = ccom @@ {x1,y1,x2,y2,x3,y3};
      
      marker=imsGetMarkers[te2dof];
      {bfX,bfY}=f[marker,comX,comY];
      newElementRHSMatrix=
        imsGetElementMatrixValues[elementRightHandSide]+
          area/3.{{bfX} , {bfY} , {bfX} , {bfY} , {bfX} , {bfY}};
      outElementRHS=
        imsMakeElementMatrix[ newElementRHSMatrix , 
          imsGetElementMatrixRows[ elementRightHandSide] , {1} ];
      {elementOperatorMatrix,outElementRHS}
      ];



End[];



Protect[];
EndPackage[] ;
