(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)







(* *)
(* Title: FEPlot.m *)
(* Context: Imtek`FEPlot` *)
(* 
  Author: Jan Lienemann *)
(* Date: 1.3.2005, Freiburg i.Br. *)
(* 
  Summary: This package provides a function to make plots for triangles with \
a linear shape function interpolating between the edges *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.2.1 *)
(* 
  Mathematica Version: 5.0 *)
(* History: 18.6.2003 initial version
      22.06.2005 FEPlot is obsolete, use UnstructuredPlot instead! *)
(* 
  Keywords: *)
(* Sources: *)
(* Warnings: *)
(* Limitations: *)
(* 
  Discussion: *)
(* Requirements: *)
(* Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* This package provides a function to make plots for triangles with a linear \
shape function interpolating between the edges *)

(* Copyright (C) 2003-2005 jan lienemann *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)
BeginPackage["Imtek`FEPlot`"];
Unprotect[imsFEContourPlot,imsFEContourPlot3D,imsFEMeshPlot,imsFEPlot3D];





(* *)
(* documentation *)
(* *)
Needs["Imtek`Maintenance`"]

(* for ims... prefix *)

imsCreateObsoleteFunctionInterface[FEContourPlot3D,$Context];
imsCreateObsoleteFunctionInterface[FEContourPlot,$Context];
imsCreateObsoleteFunctionInterface[FEMeshPlot,$Context];
imsCreateObsoleteFunctionInterface[FEPlot3D,$Context];

(* for UnstructuredPlot3D *)

imsCreateObsoleteFunctionPackageInterface[imsFEContourPlot3D,
    "Imtek`UnstructuredPlot`imsUnstructuredContourPlot3D"];
imsCreateObsoleteFunctionPackageInterface[imsFEContourPlot,
    "Imtek`UnstructuredPlot`imsUnstructuredContourPlot"];
imsCreateObsoleteFunctionPackageInterface[imsFEMeshPlot,
    "Imtek`UnstructuredPlot`imsUnstructuredMeshPlot"];
imsCreateObsoleteFunctionPackageInterface[imsFEPlot3D,
    "Imtek`UnstructuredPlot`imsUnstructuredPlot3D"];

(* functions *)

imsFEContourPlot3D::usage="imsFEContourPlot[co, inc, val] generates a contour plot of the interpolation of val over the surface triangles of tetrahedral elements specified by a list of node coordinates co and an incidence matrix inc.";\


imsFEContourPlot::usage="imsFEContourPlot[co, inc, val] generates a contour plot of the interpolation of val over the triangles specified by a list of node coordinates co and an incidence matrix inc.";\


imsFEMeshPlot::usage="imsFEMeshPlot[co, inc] generates a plot of a 2D triangular mesh specified by a list of node coordinates co and an incidence matrix inc.";\


imsFEPlot3D::usage="imsFEPlot3D[co, inc, val] generates a 3D surface plot of the interpolation of val over the triangles specified by a list of node coordinates co and an incidence matrix inc.";



Begin["`Private`"];

imsFEPlot::obsolete="Imtek`FEPlot` is obsolete. Please use Imtek`UnstructuredPlot` instead. For a short time, automatic remapping is in place. All your function are belong to us.";\

Message[imsFEPlot::obsolete];



Needs[ "Utilities`FilterOptions`" ];



(* *)
(* define your options *)
(* *)



















End[] (* of Begin Private *)



EndPackage[] ;