(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: Line.m *)
(* Context: *)
(* Author:oliver ruebenkoenig *)
(* 
  Date: 28.2.2005,Borkum *)
(* 
  Summary: This is the IMTEK template for writing a mathematica packages *)
(* 
  Package Copyright: 
      Taken from Structure and Interpretation of Computer Programms *)
(* 
  Package Version: 0.1 *)
(* Mathematica Version: 4.2 *)
(* History: *)
(* 
  Keywords: *)
(* Sources: *)
(* Warnings: *)
(* Limitations: *)
(* 
  Discussion: *)
(* Requirements: *)
(* Examples: *)
(* *)



(* Start Package *)
BeginPackage["Imtek`Queue`"];





(* *)
(* documentation *)
(* *)
Needs["Imtek`Maintenance`"]
imsCreateObsoleteFunctionInterface[ MakeQueue, $Context ];
imsCreateObsoleteFunctionInterface[ FirstQueue, $Context ];
imsCreateObsoleteFunctionInterface[ EmptyQueueQ, $Context ];
imsCreateObsoleteFunctionInterface[ InsertQueue, $Context ];
imsCreateObsoleteFunctionInterface[ DeleteQueue, $Context ];
imsCreateObsoleteFunctionInterface[ InsertQueue, $Context ];


(* constructors *)

imsMakeQueue::usage="imsMakeQueue[ ] constructs a first in first out queue object.";\


(* selectors *)

imsFirstQueue::usage = \
"imsFirstQueue[ queue ] returns the first element of the queue.";

(* predicates *)

imsEmptyQueueQ::usage = \
"imsEmptyQueueQ[ queue ] returns True if the queue is empty, False otherwise.";\


(* functions *)

imsInsertQueue::usage="imsInsertQueue[ queue, expr ] insertes expression in the last position into queue.";\


imsDeleteQueue::usage="imsDeleteQueue[ queue ] deletes the first element from the queue.";









Begin["`Private`"];





(* *)
(* define your options *)
(* *)



(* *)
(* implementation part *)
(* *)

(* constructor *)
SetAttributes[ imsQueue, HoldAll ]

imsMakeQueue[ ] := Module[
    { quList = List[] },
    imsQueue[ quList ]
    ]

Format[ imsQueue[_], StandardForm ] := "-imsQueue-"



(* selector *)
imsQueue /: imsFirstQueue[ imsQueue[ x_ ] ] := First[ x ];



(* predicates *)

imsQueue /: imsEmptyQueueQ[ imsQueue[ x_ ] ] := Length[ x ] === 0;
imsQueue /: imsEmptyQueueQ[ imsQueue[ { __ } ] ] := False;



(* functions *)

imsQueue /: imsInsertQueue[ imsQueue[ x_ ], y__ ] :=x = Flatten[ { x, y } ] ;
imsQueue /: imsDeleteQueue[ imsQueue[ x_] ] := x = Drop[ x, 1 ];



End[] (* of Begin Private *)



(* Protect[] (* anything *) *)
EndPackage[] 
