(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: ShowStatus.m *)
(* Context: *)
(* Author:oliver ruebenkoenig, 
  christian moosmann *)
(* Date: 28.2.2005, Freiburg *)
(* 
  Summary: Some long numerical computations need a way to tell their status *)
\
(* Package Copyright: GNU GPL *)
(* Package Version: 0.1.3 *)
(* 
  Mathematica Version: 5.1 *)
(* 
  History: This is from a Mathematica new group and i think from Theodoy \
Gray, the second part is from Mark Fisher *)
(* Keywords: *)
(* Sources: *)
(* 
  Warnings: *)
(* Limitations: *)
(* Discussion: *)
(* Requirements: *)
(* 
  Examples: *)
(* *)



(* Start Package *)
BeginPackage["Imtek`ShowStatus`"];





(* *)
(* documentation *)
(* *)
Needs["Imtek`Maintenance`"]
createObsoleteFunctionInterface[ ShowStatus, $Context ];
createObsoleteFunctionInterface[ ClearStatus, $Context ];
createObsoleteFunctionInterface[ ShowStatusNotebook, $Context ];
createObsoleteFunctionInterface[ ClearStatusNotebook, $Context ];

(* constructors *)

(* selectors *)

(* predicates *)

(* functions *)
imsShowStatus::usage = 
  "imsShowStatus[ expr ] prints expr in the status bar of the FrontEnd." 

imsClearStatus::usage = "imsClearStatus[] clears the status bar of the FrontEnd."
\

imsShowStatusNotebook::usage = 
  "imsShowStatusNotebook[ expr ] prints expr in a status Notebook." 

imsClearStatusNotebook::usage = 
  "imsClearStatusNotekook[] clears the status Notebook."



(* *)
(* options docu *)
(* *)







Begin["`Private`"];







(* *)
(* implementation part *)
(* *)

(* constructor *)



(* *)
(* define your options *)
(* *)



(* selector *)



(* predicates *)



(* functions *)

imsShowStatus[status_]:=
    LinkWrite[$ParentLink,
      SetNotebookStatusLine[FrontEnd`EvaluationNotebook[], 
        ToString[ status ] ] ];

imsClearStatus[]:= imsShowStatus[""];

imsShowStatusNotebook[ 
    expr_ ]:=(If[ Head[ imsStatusNotebook]\[Equal]Symbol,
      imsStatusNotebook=NotebookCreate[WindowSize\[Rule]{400,150}]];
    NotebookWrite[imsStatusNotebook,Cell[ToString[expr],"Text"],All];)

imsClearStatusNotebook[]:=(NotebookClose[imsStatusNotebook];
    Clear[imsStatusNotebook])



(* representors *)



End[] (* of Begin Private *)



(* Protect[] (* anything *) *)
EndPackage[] 
