(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: Trees.m *)
(* Context: *)
(* Author:oliver ruebenkoenig *)
(* 
  Date: 20.4.2006, Freiburg *)
(* 
  Summary: This package provides kd-Trees for coordinates *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.2.1 *)
(* 
  Mathematica Version: 5.2 *)
(* History:
    Fixed export of $imsEmptyTree;
  Fixed the distance computation in imsNearestneigbourSearch;
   *)
(* Keywords: *)
(* Sources: 
      http://
    forums.wolfram.com/mathgroup/archive/2004/Jan/
        msg00614.html and Roman Maeders Book:"Computer Science with Mathematica"
\
  *)
(* Warnings: *)
(* Limitations: *)
(* Discussion: *)
(* 
  Requirements: *)
(* Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* This package provides kd-Trees for coordinates *)

(* Copyright (C) 2006 oliver ruebenkoenig *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)
BeginPackage["Imtek`Trees`"];





(* *)
(* documentation *)
(* *)

(* constructors *)

imsMakeTreeNode::usage="imsMakeTreeNode[ info, left, right ] returns imsTreeNode with info and a left and right subtree.";\

imsMakeKDTree::usage="imsMakeKDTree[ {{x1, x2,..},..} ] returns a balanced kd-Tree for nDimensional coordinate {x1,x2,..}.";\

imsTreeNode::usage="imsTreeNode is the data structure returned by imsMakeTreeNode";\

$imsEmptyTree::usage="returns an empty tree.";

(* selectors *)

imsGetInformation::usage="imsGetInformation[ tree ] returns the information of tree.";\

imsGetLeftTree::usage="imsGetLeftTree[ tree ] returns the left subtree.";
imsGetRightTree::uase="imsGetRightTree[ tree ] returns the right subtree.";

(* predicates *)

(* functions *)

imsInsertInKDTree::usage="imsInsertInKDTree[ tree, info, dim ] returns a tree with info with dimension dim inserted.";\

imsRangeSearchKDTree::usage="imsRangeSearchKDTree[ tree, lowBound, highBound, dim] returns a list of all dim dimensional coordinates in tree which are larger than lowBound and smaller than highBound.";\

imsNearestPointSearchKDTree::usage="imsNearestPointSearchKDTree[ tree, coordinate ] returns the point in the tree which is closest to coordinate.";



(* *)
(* options docu *)
(* *)



(* *)
(* error messages *)
(* *)



Begin["`Private`"];



(* *)
(* private imports *)
(* *)
Needs["Imtek`Point`"];



(* *)
(* implementation part *)
(* *)

(* constructor *)
(* *)
$imsEmptyTree = {};

imsMakeTreeNode[  info_, left_, right_ ] := imsTreeNode[ info, left, right ];

imsMakeKDTree[ data_List ] :=
  Fold[ Function[ {tree,info }, 
      imsInsertInKDTree[ tree, info, 
        Last[ Dimensions[ data ] ] ] ], $imsEmptyTree, 
    imsBalanceKDTree[ data, Last[ Dimensions[ data ] ]  ] ]



(* *)
(* define your options *)
(* *)



(* selector *)
(* *)
imsGetInformation[ imsTreeNode[ info_, _, _ ] ] := info;
imsGetLeftTree[ imsTreeNode[ _, left_, _ ] ] := left;
imsGetRightTree[ imsTreeNode[ _, _, right_ ] ] := right;



(* predicates *)
(* *)



(* private functions *)
(* *)

imsBalanceKDTree[ $imsEmptyTree,dim_, index_:1 ] := $imsEmptyTree;
imsBalanceKDTree[ pts_, dim_, index_:1 ] := Block[
    { mid = Ceiling[ Length[ pts ] / 2 ], 
      order = Ordering[ pts[[ All,index ]] ] },
    Join[
      pts[[order[[ { mid } ]] ]],
      imsBalanceKDTree[ pts[[ Take[ order, { 1, mid - 1 } ] ]], dim, 
        Mod[ index + 1, dim,1 ] ],
      imsBalanceKDTree[ pts[[ Take[ order, { mid + 1,-1 } ] ]], dim, 
        Mod[ index + 1, dim,1 ] ]
      ]
    ]

(* public functions *)
(* *)

imsInsertInKDTree[ $imsEmptyTree, info_, dim_, index_:1 ] := 
    imsMakeTreeNode[ info, $imsEmptyTree, $imsEmptyTree ];

imsInsertInKDTree[ tree:imsTreeNode[ treeInfo_, left_, right_ ], info_, dim_, 
        index_:1 ] /; Order[ info, treeInfo ] \[Equal]0 := tree;

imsInsertInKDTree[ tree:imsTreeNode[ treeInfo_, left_, right_ ], info_, dim_, 
        index_:1 ] /; info[[ index ]] <  treeInfo[[ index ]] := 
    imsMakeTreeNode[
      treeInfo,
      imsInsertInKDTree[ left, info,dim, Mod[ index+1, dim, 1 ] ],
      right
      ];

imsInsertInKDTree[ tree:imsTreeNode[ treeInfo_, left_, right_ ], info_, 
      dim_,  index_:1 ]:= imsMakeTreeNode[
      treeInfo,
      left,
      imsInsertInKDTree[ right, info, dim, Mod[ index+1, dim, 1 ] ]
      ];

imsRangeSearchKDTree[ {}, lowBound_, highBound_, dim_, index_:1 ] := {};

imsRangeSearchKDTree[ tree:imsTreeNode[ info_, left_, right_ ], lowBound_, 
    highBound_, dim_, index_:1 ] :=
  List[
    If[(And @@ 
          Thread[ lowBound \[LessEqual] info \[LessEqual] highBound ]),{  
        imsGetInformation[ tree ] },{} ],
    If[ (lowBound[[ index ]] \[LessEqual] info[[ index ]]), 
      imsRangeSearchKDTree[ left, lowBound, highBound, dim, 
        Mod[ index +1, dim, 1 ] ],{}],
    If[ (info[[ index ]] < highBound[[ index ]]), 
      imsRangeSearchKDTree[ right, lowBound, highBound, dim, 
        Mod[ index +1, dim, 1 ] ],{}]
    ]

imsNearestPointSearchKDTree[ tree_,pnt_ ]:=Module[
    { nspKD, lowBound={-Infinity,-Infinity}, highBound={Infinity,Infinity}, 
      d=Infinity,d2,nearestPnt,dim },
    
    nspKD[{},index_, dim_] := {};
    
    nspKD[imsTreeNode[ info_, left_, right_ ],index_, dim_]:= 
      CompoundExpression[
        If[(d2= imsDistance[ { info, pnt } ])<d,d=d2;
          nearestPnt=info;{lowBound,highBound}={pnt-d,pnt+d};];
        If[ lowBound[[ index ]]\[LessEqual]info[[ index ]], 
          nspKD[ left, Mod[ index +1,dim, 1 ], dim ] ];
        If[ info[[ index ]] < highBound[[ index ]], 
          nspKD[ right, Mod[ index + 1,dim,1 ], dim ] ]
        ];
    
    dim = Last[ Dimensions[ imsGetInformation[ tree ] ] ];
    nspKD[tree,1, dim];
    Return[ nearestPnt ]
    ]





(* representors *)
(* *)



(* Begin Private *)
End[]



(* Protect[] *)
EndPackage[] 
