(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)











BeginPackage["Imtek`VectorAngles`"];
VectorAngles::"usage"=
    "The VectorAngles package provides some functions with which to compute \
vector angles. Also see \!\(\*
StyleBox[\"vectorAngle\",\nFontSlant->\"Italic\"]\), \!\(\*
StyleBox[\"filterAngles\",\nFontSlant->\"Italic\"]\) and \!\(\*
StyleBox[\"unitRightVector\",\nFontSlant->\"Italic\"]\).";
vectorAngle::"usage"=
    "vectorAngle[{x_,y_}] computes the angle that a vector centered at the \
origin makes with the horizontal x-axis. The angle is returned modula \
2\[Pi].";
filterAngles::"usage"="filterAngles[{\[Theta]1,\[Theta]2}] returns its \
arguments in a form correct for the Mathematica Circle and Disk Graphics \
primitives, i.e., the first angle is smaller than the second.";
unitRightVector::"usage"=
    "unitRightVector[{x,y}] produces a vector perpendicular to the \
origin-based vector argument {x,y} that represents a right turn in the plane. \
The resultant vector is normed.";

Begin["`Private`"];





\!\(\(\(vectorAngle[{x_, y_}] := 
      Module[{l, \[Theta]}, \[IndentingNewLine]l = \@\(x\^2 + y\^2\); \
\[IndentingNewLine]If[
          l \[Equal] 0, \[IndentingNewLine]\[Theta] = 
            0, \[IndentingNewLine]If[
            x \[GreaterEqual] 
              0, \[IndentingNewLine]\[Theta] = \(-ArcSin[
                  y/l]\), \[IndentingNewLine]\[Theta] = 
              ArcSin[y/
                    l] - \[Pi]\[IndentingNewLine]]\[IndentingNewLine]]; \
\[IndentingNewLine]Return[Mod[\[Theta], 2  \[Pi]]]\  (*\ 
          Angles\ must\ lie\ between\ 0\ and\ 2  \[Pi]\ \
*) \[IndentingNewLine]];\)\(\[IndentingNewLine]\)
  \)\[IndentingNewLine]
  \(\(filterAngles[{\[Theta]1_, \[Theta]2_}] := 
    If[\[Theta]1 > \[Theta]2, Return[{\[Theta]1 - 2  \[Pi], \[Theta]2}], 
      Return[{\[Theta]1, \[Theta]2}]]\)\( (*\ 
    angle\ ranges\ must\ be\ from\ small\ to\ large\ *) \)\(\
\[IndentingNewLine]\)
  \)\[IndentingNewLine]
  \(unitRightVector[{x_, y_}] := 
      Module[{l}, \[IndentingNewLine]l = \@\(x\^2 + y\^2\); \
\[IndentingNewLine]Return[{y, \(-x\)}/l]\[IndentingNewLine]];\)\)



End[];
EndPackage[];
