(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: Ply2.m *)
(* Context: *)
(* Author:Jan G. Korvink *)
(* 
  Date: 10.01.2005, Freiburg *)
(* 
  Summary: Conversion of Ply2 format to Graphics3D *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.1.1 *)
(* 
  Mathematica Version: 4.2 *)
(* History: *)
(* Keywords: *)
(* Sources: *)
(* 
  Warnings: *)
(* Limitations: *)
(* Discussion: *)
(* Requirements: *)
(* 
  Examples: *)
(* *)



(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* <Imports Ply2 files and returns result as Graphics3D object.> *)

(* Copyright (C) <2005> <Jan G. Korvink> *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)













(* Start Package *)
BeginPackage["Imtek`Interfaces`Ply2`"];





(* *)
(* documentation *)
(* *)

(* functions *)
Ply2ToGraphics3D::usage = 
  "Ply2ToGraphics3D[ ply2filename ] returns the Graphics3D version of the object in the ply2 file" 











Begin["`Private`"];







(* *)
(* implementation part *)
(* *)

(* constructor *)
(* MakeLine[ a_?PointQ, b_?PointQ ] := Line[ a, b ]; *)



(* *)
(* define your options *)
(* *)
(* 
  Options[ myFunctio ] = { myOptionName \[Rule] myValue } *)




(* selector *)
(*
  Unprotect[ Line ];
  Line /: GetLineStart[ Line[ a_, b_ ] ] := a;
  Line /: GetLineEnd[ Line[ a_, b_ ] ] := b;
  Protect[ Line ];
  *)



(* predicates *)
(*
  Unprotect[ Line ];
  Line /: LineQ[ Line[ a_, b_ ] ] := True;
  Protect[ Line ];
  LineQ[ ___ ] := False;
  *)



(* *)
(* public functions *)
(* *)

Ply2ToGraphics3D[filename_String]:=
    Module[{f,npoints,ntriangles,coords,triangles},
      
      f=OpenRead[filename];
      {npoints,ntriangles}=Read[f,{Number,Number}];
      coords=ReadList[f,{Real,Real,Real},npoints];
      triangles=ReadList[f,{Number,Number,Number,Number},ntriangles];
      Close[f];
      
      (* Note: 
          Ply2 files use 0 based addressing: {0,1,2,...}. 
                  Mathematica is 1 based: {1,2,3,...}
        *)
      
      Graphics3D[{EdgeForm[],
          Polygon[Join[#,{#[[1]]}]]&/@(coords[[Drop[#,1]+{1,1,1}]]&/@
                triangles)}]
      ];

(* *)
(* private functions *)
(* *)



(* representors *)
(*
  Unprotect[ Graphics ];
  
  Graphics[ aLineList:{_Line ..} , options___ ]:=
     Graphics[ Line[ 
        Through[ List[ GetPointX, GetPointY ][ # ] ] & /@Flatten[ 
            Through[ List[GetLineStart, GetLineEnd][ # ] ] & /@ aLineList
            ]
         ], options
      ] ;
  
  Protect[ Graphics ];
  *)



End[] (* of Begin Private *)



(* Protect[] (* anything *) *)
EndPackage[] 
