(*******************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which
typically will have the same name as this file except ending in
".nb" instead of ".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent
to using the Evaluate Initialization Cells menu command in the front
end.

DO NOT EDIT THIS FILE.  This entire file is regenerated
automatically each time the parent Notebook file is saved in the
Mathematica front end.  Any changes you make to this file will be
overwritten.
***********************************************************************)





(* *)
(* Title: TetgenInterface.m *)
(* Context: *)
(* 
  Author: oliver ruebenkoenig and christian moosmann *)
(* 
  Date: 16.1.2006, Freiburg *)
(* 
  Summary: This is the IMTEK package for generating Tetgen input files *)
(* 
  Package Copyright: GNU GPL *)
(* Package Version: 0.1.1 *)
(* 
  Mathematica Version: 5.2 *)
(* History:
    backward compatability for 5.0 
      fixed the documentation;
  fixed bug in quadratic tetgen read;
  finished read tetgen;
  added first version of read tetgen
    modification of TriangleInterface for use with tetgen
   *)
(* Keywords: *)
(* Sources: Tetgen is a mesh generator *)
(* 
  Warnings: *)
(* Limitations: *)
(* Discussion: *)
(* Requirements: *)
(* 
  Examples: *)
(* *)



(* Disclaimer *)

(* Whereever the GNU GPL is not applicable, 
  the software should be used in the same spirit. *)

(* Users of this code must verify correctness for their application. *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)

(* Disclaimer: *)

(* This is the IMTEK package for generating Tetgen input files. *)

(* Copyright (C) 2005-2006 oliver ruebenkoenig and christian moosmann *)

(* This program is free software; *)

(* you can redistribute it and/
      or modify it under the terms of the GNU General Public License *)

(* as published by the Free Software Foundation;
  either version 2 of the License, *)

(* or (at your option) any later version.This program is distributed in the \
hope that *)

(* it will be useful,but WITHOUT ANY WARRANTY; *)

(* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE. *)

(* See the GNU General Public License for more details. 
      You should have received a copy of *)

(* the GNU General Public License along with this program;if not, 
  write to the *)

(* Free Software Foundation,Inc.,59 Temple Place,Suite 330,Boston,
  MA 02111-1307 USA *)



(* Start Package *)

BeginPackage[
    "Imtek`Interfaces`TetgenInterface`", { "Imtek`Graph`", "Imtek`Nodes`",
      "Imtek`DomainElementLibrary`", "Imtek`MeshElementLibrary`" } ];





(* *)
(* documentation *)
(* *)

(* constructors *)

(* selectors *)

(* predicates *)

(* functions *)

imsToTetgenInputFile::usage = \
"imsToTetgenInputFile[ domain, {holePoints}, {markerPoints} ] returns an input file for tetgen. Domain is a nexus. Optionally a list of hole points { x, y, z } and a list of marker points { { x, y, z }, marker, delimiter } can be given. The delimiter controls the mesh size at this point.";\


imsReadTetgenOutput::usage = "imsReadTetgenOutput[file, boundaryMarkers, boundaryFunction, boundaryData ] returns a nexus generated from tetgen output file. Optionally the functions boundaryMarkers[ id, x, y, z ], boundaryFunction[id, x, y, z, marker] and boundaryData[id, x, y, z, marker] can be given.";



(* *)
(* options docu *)
(* *)



(* *)
(* error messages *)
(* *)



Begin["`Private`"];



(* *)
(* private imports *)
(* *)



(* *)
(* implementation part *)
(* *)

(* constructor *)
(* *)



(* *)
(* define your options *)
(* *)



(* selector *)
(* *)



(* predicates *)
(* *)



(* private functions *)
(* *)

(* public functions *)
(* *)

imsToTetgenInputFile[ nexus_imsNexus, pointsMarkingHoles_:{{}}, 
      pointsMarkingDomains_:{{}}  ] := 
    Module[ { nodes, numberOfNodes, firstLine, nodeLines,segments,
        segmentHoles, numberOfSegments, firstSegmentLine, segmentLines, 
        numberOfHoles, holePoints,segmentHolePoints, numberOfDomains, 
        domainPoints, i,tempinc },
      
      nodes = imsGetNodes[ nexus ];
      numberOfNodes  = Length[ nodes ];
      segments = Cases[imsGetElements[ nexus ],_imsDomainSegment];
      segmentHoles= Cases[imsGetElements[ nexus ],_imsDomainHoleSegment];
      segmentHolePoints=
        Apply[Plus,imsGetCoords[nodes[[#]]]]/Length[#]&/@
          imsGetIncidentsIds/@segmentHoles;
      numberOfSegments = Length[ segments ];
      
      firstLine = { { numberOfNodes, 3, 0, 1 } };
      nodeLines = 
        Flatten[{ imsGetIds[ # ], imsGetCoords[ # ], 
                imsGetMarkers[ # ] } ] &  /@ nodes;
      
      firstSegmentLine = { { numberOfSegments, 1 } };
      
      
      segmentLines =
        Flatten[Switch[imsDataDomainElementQ[#],
                False,{{1,0,imsGetMarkers[#]},
                  Flatten[{Length[tempinc=imsGetIncidentsIds[ # ]], 
                      tempinc}]},
                True,
                Join[Join[{{1+Length[imsGetDatas[#]],Length[imsGetDatas[#]],
                        imsGetMarkers[#]},
                      Flatten[{Length[tempinc=imsGetIncidentsIds[ # ]], 
                          tempinc}]},
                    Flatten[{Length[tempinc=imsGetIncidentsIds[ # ]], 
                            tempinc}]&/@segmentHoles[[imsGetDatas[#]]]],i=1;
                  Flatten[ {i++,segmentHolePoints[[imsGetIds[#]]] } ]&/@
                    segmentHoles[[imsGetDatas[#]]]]
                ] & /@ segments ,1];
      
      If[
        MatchQ[ pointsMarkingHoles, {{ _,_ ,_}..} ],
        numberOfHoles = {{ Length[ pointsMarkingHoles ] }};
        i=1;
        holePoints = Flatten[ { i++, # } ]& /@ pointsMarkingHoles,
        numberOfHoles = {{ 0 }};
        holePoints = {{" "}}
        ];
      
      If[
        MatchQ[ pointsMarkingDomains, {{ {_,_, _ },_,_}..} ],
        numberOfDomains = {{ Length[ pointsMarkingDomains ] }};
        i=1;
        domainPoints = Flatten[ { i++, # } ]& /@ pointsMarkingDomains,
        numberOfDomains = {{ 0 }};
        domainPoints = {{" "}}
        ];
      
      Return[ 
        Join[ firstLine, nodeLines, firstSegmentLine, segmentLines, 
          numberOfHoles, holePoints, numberOfDomains, domainPoints ] ];
      ];



imsReadTetgenOutput[ fileName_, 
    markerFunction_:Function[ { id, x, y, z, marker }, marker ], 
    boundaryFunction_:Function[ { id, x, y, z, marker }, {{ 0 }} ], 
    boundaryData_:Null ] := imsReadTetgenOutput[ 
    { (* generate the correct file names for .node and .ele *)
      
      StringJoin[ 
        Join[ { DirectoryName[ fileName ] },
          StringJoin[ #, "." ]& /@ 
            Drop[ StringSplit[ 
                StringReplace[ fileName, 
                  DirectoryName[ fileName ] \[Rule] "" ],
                "." ],-1  ], {"node"} ]  ],
      StringJoin[ 
        Join[ { DirectoryName[ fileName ] },
          StringJoin[ #, "." ]& /@ 
            Drop[ StringSplit[ 
                StringReplace[ fileName, 
                  DirectoryName[ fileName ] \[Rule] "" ],
                "." ],-1  ], {"ele"} ]  ]
       }, markerFunction, boundaryFunction, boundaryData ]

imsReadTetgenOutput[ { nodeFileName_, elementFileName_ },  
      markerFunction_:Function[ { id, x, y, z, marker }, marker ],
      boundaryFunction_:Function[ { id, x, y, z, marker }, {{ 0 }} ], 
      boundaryData_:Null ] := Module[
      {
        rawNodes, rawElements,
        numberOfElements, orderOfElement, boolMarker,
        elementType, elementIdPattern, elementIds,elementMarkerPattern, 
        elementMarkers,boolElementMarker,
        elementParsePattern,  elementParseAccess,
        interiorNodes, boundaryNodes, thisMarker, elements
        },
      
      (* read the data *)
      rawNodes = Import[ nodeFileName, "Table" ];
      rawElements = Import[ elementFileName, "Table" ];
      
      interiorNodes = 
        Select[ Take[ rawNodes, {2, -2 } ], ( Last[ # ] == 0& ) ] /. { 
              id_Integer, xCoord_, yCoord_, zCoord_, nodeMarker_ } \[Rule] 
            imsMakeNode[ id, { xCoord, yCoord, zCoord }  ];
      
      Which[
        boundaryData =!= Null,
        boundaryNodes = 
          Select[ Take[ rawNodes, {2, -2 } ], ( Last[ # ] != 0& ) ] /.{ 
                id_Integer, xCoord_, yCoord_,zCoord_, nodeMarker_ } :>
              imsMakeNode[ id, { xCoord, yCoord,zCoord }, 
                
                thisMarker = 
                  markerFunction[ id, xCoord, yCoord, zCoord, nodeMarker ], 
                boundaryFunction[ id, xCoord, yCoord,zCoord, thisMarker ], 
                boundaryData[ id, xCoord, yCoord,zCoord, thisMarker ] ],
        boundaryData === Null,
        boundaryNodes = 
          Select[ Take[ rawNodes, {2, -2 } ], ( Last[ # ] != 0& ) ] /.{ 
                id_Integer, xCoord_, yCoord_,zCoord_, nodeMarker_ } :>
              imsMakeNode[ id, { xCoord, yCoord,zCoord }, 
                
                thisMarker = 
                  markerFunction[ id, xCoord, yCoord, zCoord, nodeMarker ], 
                boundaryFunction[ id, xCoord, yCoord,zCoord, thisMarker ] ]
        ];
      
      { numberOfElements, orderOfElement, boolElementMarker } = 
        First[ rawElements ];
      
      Which[
        orderOfElement \[Equal] 4,
        elementType = imsMakeTetrahedronLinear1DOF;
        elementIdPattern = { id1_, id2_, id3_, id4_ };
        elementIds = { id1, id2, id3, id4 }
        ,
        
        orderOfElement \[Equal] 10,
        elementType = imsMakeTetrahedronQuadratic1DOFSerendipity;
        elementIdPattern = { id1_, id2_, id3_, id4_, id5_ ,id6_, id7_, id8_, 
            id9_, id10_ }; 
        elementIds = {id1,id2,id3,id4,id5,id6,id7,id9,id10,id8}
        ,
        
        True, Print["Element Order: ", orderOfElement, " not supported."];
        ];
      
      Which[
        boolElementMarker \[Equal] 0,
        elementMarkerPattern = {};
        elementMarkers = Sequence[]
        ,
        
        boolElementMarker \[Equal] 1,
        elementMarkerPattern = { marker_ };
        elementMarkers = marker
        ,
        True, Print["Marker: ", boolMarker, " not supported."];
        ];
      
      elementParsePattern = 
        Flatten[ { id_Integer, elementIdPattern, elementMarkerPattern } ];
      elementParseAccess = Sequence[ id, elementIds, elementMarkers ];
      
      elements = 
        Take[ rawElements, { 2, -2 } ] /. 
          elementParsePattern \[Rule] (elementType[ elementParseAccess ]);
      
      Return[ imsMakeNexus[ boundaryNodes, interiorNodes, elements ] ];
      ];



(* representors *)
(* *)



(* Begin Private *)
End[]



(* Protect[] *)
EndPackage[] 
